apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "common.names.fullname" . }}-openvpn-pre-start-sh
  labels:
    {{- include "common.labels" . | nindent 4 }}
data:
  openvpn-pre-start.sh: |
    #!/bin/bash
    for file in /etc/openvpn/mullvad/*.ovpn; do 
      if [ -f "$file" ]; then 
        echo "" >> "$file"
        echo 'pull-filter ignore "dhcp-option DNS6"' >> "$file"
        echo 'pull-filter ignore "tun-ipv6"' >> "$file"
        echo 'pull-filter ignore "ifconfig-ipv6"' >> "$file" 
      fi
    done
